### ISSUE TITLE
programs_all_thre_0.1_final_new.xls

### ISSUE THREAD

**Issue by Georgewwek** [ruoyan-li/Cutaneous-T-cell-lymphoma-study#1]
Thank you for sharing this amazing repository! I have learned a lot from your work.
I have a quick question regarding the NMF_programs.ipynb notebook. Specifically, I noticed the file programs_all_thre_0.1_final_new.xls being used in the code. Could you kindly explain how this file was generated? Any details or pointers would be greatly appreciated!

**Comment by ruoyan-li** [comment]
Thanks for reaching out. It's the same table as Supplementary Table 3 of the paper. Basically, we just merged every intra-tumour expression program gene list from all tumours (each column represents a intra-tumour program).

**Comment by ruoyan-li** [comment]
> notebook

Thanks for reaching out. It's the same table as Supplementary Table 3 of the paper. Basically, we just merged every intra-tumour expression program gene list from all tumours (each column represents a intra-tumour program).

**Comment by ruoyan-li** [comment]
Thanks for reaching out @Georgewwek. It's the same table as Supplementary Table 3 of the paper. Basically, we just merged every intra-tumour expression program gene list from all tumours (each column represents a intra-tumour program).
