### ISSUE TITLE
Trouble finding the sequencing files and matching the GEX and VDJ for respective patients

### ISSUE THREAD

**Issue by ryanreis333** [ruoyan-li/Cutaneous-T-cell-lymphoma-study#2]
Thank you for providing this repo to accompany a great paper! I'm hoping to use some of your newly generated scRNA/VDJ seq data but I'm having some trouble finding it all. It seems as though there are some issues with both options I've tried and are below:

Option 1: download and use the deposited objects on cell atlas

Issue: I'm really hoping to attach the VDJ seq data to the object, and it doesn't look like any of this is included in the objects. Is there a way to share that info so that I can assign VDJ sequences and clonotype information to each cell?

Option 2: redownload the GEX and VDJ files from https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-12303 and rebuild the objects, attaching the VDJ info when creating them.

Issue: It isn't clear to me what samples are what and which VDJ files go with which GEX files. I only see 3 CTCL files (CTCL2-4) along with many WSSS files. Is there a difference between these? Does each CTCL2/3/4 correspond to a single patient, or does the number after the GEX/VDJ in the name (1/2/3/4/etc) distinguish different patients? I would expect there to be 18 GEX files and 18 VDJ files, but I'm having a hard time understanding what is what.

Any help would be much appreciated!

Thank you

**Comment by ruoyan-li** [comment]
Thank you for pointing this out. I’ve uploaded a VDJ table here: https://drive.google.com/file/d/1eGwRagALcUudxC-lp9vuN4_wEtuT_iyh/view?usp=sharing, and I hope it meets your needs. 
Just to clarify: among the 18 newly generated samples, only 8 have VDJ data. The remaining 10 were derived from FFPE samples using the 10x Flex.
We will be also working on adding a table to indicate the correspondence between samples and files at arrayexpress.

**Comment by ryanreis333** [comment]
Really appreciate the quick response and for clarifying which samples have the VDJ info. Looking at the paper, it seems like you used 10X's CellRanger vdj to align the VDJ seq. That csv above could work for us, but do you happen to have and mind sharing the filtered contig annotations csv files for easy integration into a seurat object? (Also, just because I'm not sure, what file type is that csv you shared above? Is that one of the outputs of cellranger or a csv you created from the outputs?) Thanks again

**Comment by ruoyan-li** [comment]
Here you go: https://drive.google.com/file/d/1mJTo_vy1swGMBuATR9grFV-QurZdmOZ1/view?usp=sharing

**Comment by ryanreis333** [comment]
That looks to be exactly what we were hoping for -- thanks so much for your help!

**Comment by ryanreis333** [comment]
> Here you go: https://drive.google.com/file/d/1mJTo_vy1swGMBuATR9grFV-QurZdmOZ1/view?usp=sharing

Looks like there aren't quite the number of VDJ files here as I would expect -- sent you an email with more details.

**Comment by ruoyan-li** [comment]
Just replied to your email

**Comment by Pacomito** [comment]
Hello,

Thank you for this very complete and interesting study. 

I was also wondering if you could provide the filtered contig annotations csv files that I could integrate with the anndata you provided at https://collections.cellatlas.io/ctcl (CTCL scRNA-seq dataset)?

I checked the files you provided at https://drive.google.com/file/d/1mJTo_vy1swGMBuATR9grFV-QurZdmOZ1/view?usp=sharing but I did not managed to match the barcodes to the observation names in the anndata. 

Or if you indicate how I can match the two, this would be greatly appreciated,

Best,
Pacome

**Comment by ruoyan-li** [comment]
This table shows how you can match VDJ with GEX barcodes. 
[VDJ file.docx](https://github.com/user-attachments/files/18493675/VDJ.file.docx)

**Comment by Pacomito** [comment]
Thank you for your rapid answer,
I successfully  managed to match the VDJ to the single-cell.
